// A read-only task activity surface, not a second editor or execution runtime.
const el=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;};
const labels={queued:'排队中',running:'执行中',cancelling:'正在取消',completed:'已完成',failed:'失败',cancelled:'已取消',interrupted:'已中断 · 待核实',unknown:'状态待核实'};
const tasks=new Map(),subscribers=new Set();let selected=null,version=0,fetchVersion=0,detailVersion=0,lastFocus=null,poll,listSignature='',detailSignature='',publishedSignature='';
const css=el('link');css.rel='stylesheet';css.href='/development-tasks.css';document.head.append(css);
const panel=el('aside');panel.className='development-task-activity';panel.hidden=true;panel.setAttribute('aria-label','后台开发任务');
const header=el('header'),heading=el('h2','后台任务'),refreshButton=el('button','刷新'),close=el('button','收起');header.append(heading,refreshButton,close);
const notice=el('p');notice.setAttribute('role','status');const list=el('div');list.className='development-task-list';const detail=el('section');detail.className='development-task-detail';panel.append(header,notice,list,detail);document.body.append(panel);
const launcher=el('button','后台任务');launcher.className='chip-btn';launcher.setAttribute('aria-expanded','false');document.querySelector('.top-actions')?.append(launcher);
async function request(url,options={}){const response=await fetch(url,{...options,signal:AbortSignal.timeout(15000),headers:{'Content-Type':'application/json',...options.headers}});const data=await response.json();if(!response.ok)throw Error(data.error||'后台任务服务暂未连接');return data;}
function publish(){const values=[...tasks.values()],signature=JSON.stringify(values);if(signature!==publishedSignature){publishedSignature=signature;for(const fn of subscribers)try{fn(values)}catch{}}render();}
function render(){const signature=JSON.stringify([selected,[...tasks.values()].map(t=>[t.id,t.title,t.status,t.uncertaintyAcknowledgedAt])]);if(signature===listSignature)return;listSignature=signature;list.replaceChildren();for(const t of tasks.values()){const b=el('button');b.className='development-task-row';b.setAttribute('aria-pressed',String(t.id===selected));b.append(el('strong',t.title||'开发任务'),el('small',t.status==='interrupted'&&t.uncertaintyAcknowledgedAt?'已中断 · 已核实':labels[t.status]||t.status));b.onclick=()=>open(t.id);list.append(b)}if(!tasks.size)list.append(el('p','还没有后台开发任务。可在聊天中“交给开发”。'));}
async function refresh(){const seq=++fetchVersion,start=version;try{const data=await request('/api/development/tasks');if(seq!==fetchVersion||start!==version)return;tasks.clear();for(const t of data.tasks||[])if(typeof t.id==='string')tasks.set(t.id,t);publish();notice.textContent=typeof data.waitingReason==='string'&&data.waitingReason.trim()?data.waitingReason:data.blocked?'队列已隔离：上次执行状态待核实，请检查相关任务后确认。':data.externalBusy?'开发工作台正在执行其他任务，队列等待空闲。':'任务独立执行，聊天可继续。';}catch(e){if(seq===fetchVersion)notice.textContent=e.message;}}
function renderDetail(task,events){const signature=JSON.stringify([task,events||[]]);if(signature===detailSignature)return;detailSignature=signature;detail.replaceChildren();detail.append(el('h3',task.title||'开发任务'),el('p',task.status==='interrupted'&&task.uncertaintyAcknowledgedAt?'已中断 · 已核实':labels[task.status]||task.status));const text=task.result?.text||task.error||task.lastError;if(text){const result=el('pre',String(text));result.className='development-task-result';detail.append(result)}
 if(task.executionPlan){const tree=el('section');tree.append(el('h4','任务拆解与验收'),el('p',task.executionPlan.decision?.mode==='planned'?'Jev：复杂任务 · 规划 → 执行 → 验收':'Jev：单执行任务'));for(const node of task.executionPlan.nodes||[]){const row=el('p');row.textContent=(node.status==='completed'?'✓ ':node.status==='failed'?'! ':'· ')+node.title+' · '+(labels[node.status]||node.status);tree.append(row);}if(task.executionPlan.verification)tree.append(el('p','模型验收：'+(task.executionPlan.verification.passed?'通过':'未通过')+' · '+task.executionPlan.verification.summary));detail.append(tree);}
 const log=el('div');log.className='development-task-events';for(const event of (events||[]).slice(-100)){const entry=el('pre');const data=event.payload||event;entry.textContent=String(data.assistantMessageEvent?.delta||data.delta||data.text||data.error||event.message||event.type||'状态更新');log.append(entry)}detail.append(log);
 if(task.executionUncertain&&!task.uncertaintyAcknowledgedAt){detail.append(el('p','上次执行是否停止尚待核实。先检查工作台会话、进程和文件结果；核实不会重放旧任务。'));const checked=el('button','我已核实执行状态');checked.onclick=async()=>{if(!window.confirm('确认你已检查上次执行与残留进程，并允许队列继续？此操作不会重试旧任务。'))return;checked.disabled=true;try{await request('/api/development/tasks/'+encodeURIComponent(task.id)+'/acknowledge',{method:'POST',body:JSON.stringify({executionChecked:true})});await loadDetail(task.id);await refresh()}catch(e){notice.textContent=e.message;checked.disabled=false}};detail.append(checked)}
 if(task.isolation==='copy'){detail.append(el('p','独立项目副本 · 不自动合并到原项目（非安全沙箱）'));const workspace=task.link?.workspace||task.result?.workspace;if(workspace)detail.append(el('pre','产物目录：'+workspace));}
 const link=task.link||task.result;if(link?.conversationId){detail.append(el('p',`工作台会话 ${link.conversationId} · ${link.sessionId||''}`));const view=el('button','在开发工作台查看');view.onclick=async()=>{try{if(!window.piWorkbench?.inspectTask)throw Error('工作台查看入口尚未就绪');await window.piWorkbench.inspectTask(task);hide();notice.textContent='已打开工作台；不会接管或重新派发任务。';}catch(e){notice.textContent=e.message}};detail.append(view)}
 if(['queued','running'].includes(task.status)){const cancel=el('button','取消此任务');cancel.onclick=async()=>{if(!window.confirm('取消此后台开发任务？已产生的文件修改不会自动回滚。'))return;cancel.disabled=true;try{const data=await request('/api/development/tasks/'+encodeURIComponent(task.id)+'/cancel',{method:'POST',body:'{}'});tasks.set(data.task.id,data.task);publish();await loadDetail(task.id)}catch(e){notice.textContent=e.message;cancel.disabled=false}};detail.append(cancel)}
}
async function loadDetail(id){const seq=++detailVersion;try{const [data,history,orchestration]=await Promise.all([request('/api/development/tasks/'+encodeURIComponent(id)),request('/api/development/tasks/'+encodeURIComponent(id)+'/events'),request('/api/development/plan/'+encodeURIComponent(id)).catch(()=>({plan:null}))]);if(orchestration?.plan)data.task.executionPlan=orchestration.plan;if(seq!==detailVersion||selected!==id||panel.hidden)return;tasks.set(id,data.task);render();renderDetail(data.task,history.events||data.task.events);}catch(e){if(seq===detailVersion)notice.textContent=e.message;}}
async function open(id){lastFocus=document.activeElement;panel.hidden=false;launcher.setAttribute('aria-expanded','true');if(id)selected=id;await refresh();if(selected)await loadDetail(selected);clearInterval(poll);poll=setInterval(()=>{if(!panel.hidden){refresh();if(selected)loadDetail(selected)}},3000);close.focus();}
function hide(){panel.hidden=true;launcher.setAttribute('aria-expanded','false');clearInterval(poll);detailVersion++;lastFocus?.focus();}
launcher.onclick=()=>panel.hidden?open():hide();close.onclick=hide;refreshButton.onclick=()=>{refresh();if(selected)loadDetail(selected)};panel.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();hide()}});
window.addEventListener('pi-runtime-event',({detail:event})=>{if(event?.type!=='development_task')return;const t=event.payload?.task;if(!t?.id)return;version++;tasks.set(t.id,t);publish();if(!panel.hidden&&selected===t.id)loadDetail(t.id)});
window.addEventListener('pagehide',()=>clearInterval(poll));
window.piDevelopmentTasks={open,refresh,getTasks:()=>[...tasks.values()],subscribe:fn=>{subscribers.add(fn);return()=>subscribers.delete(fn)},async enqueue(body){const data=await request('/api/development/tasks',{method:'POST',body:JSON.stringify(body)});version++;tasks.set(data.task.id,data.task);publish();return data.task;}};

refresh();
