'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
// Reuse upstream MIT schedule normalization/time arithmetic; this facade owns cross-harness completion and abort semantics.
const {normalizeSchedulerInput,computeNextFire,SCHEDULER_HISTORY_MAX}=require('./external/pi-web-ui/dist/server/scheduler-tasks.js');
function createScheduler({dataDir,runTask,isBusy=()=>false,onEvent=()=>{},clock=()=>Date.now()}={}){
 if(!dataDir||typeof runTask!=='function')throw Error('dataDir/runTask required');
 fs.mkdirSync(dataDir,{recursive:true});const file=path.join(dataDir,'tasks.json');const time=()=>Number(typeof clock==='function'?clock():clock.now());const iso=()=>new Date(time()).toISOString();
 let tasks=[];if(fs.existsSync(file)){const saved=JSON.parse(fs.readFileSync(file,'utf8'));if(!Array.isArray(saved.tasks))throw Error('Invalid tasks store');tasks=saved.tasks;}
 const active=new Map(),blockedHarnesses=new Set(tasks.filter(t=>t.workerCleanupRequired).map(t=>t.harness));let closed=false;
 const clone=x=>JSON.parse(JSON.stringify(x));const fail=(message,status=400)=>{const e=Error(message);e.status=status;throw e};
 function save(){const temp=file+'.'+process.pid+'.tmp';fs.writeFileSync(temp,JSON.stringify({version:1,tasks},null,2),{mode:0o600});fs.renameSync(temp,file);}
 function emit(type,task,extra={}){try{onEvent({type,task:clone(task),...extra})}catch{}}
 for(const t of tasks){if(['running','cancelling'].includes(t.status)){t.status='interrupted';t.enabled=false;t.nextRunAt=null;t.workerCleanupRequired=true;blockedHarnesses.add(t.harness);t.lastError='应用重启中断；请确认上次执行结果后手动恢复';for(const h of t.history||[])if(h.status==='running'){h.status='interrupted';h.finishedAt=iso();h.error=t.lastError;}}}save();
 function get(id){const t=tasks.find(t=>t.id===id);if(!t)fail('任务不存在',404);return t;}
 function text(v,max,label){if(typeof v!=='string'||!v.trim()||v.length>max)fail(label+'无效');return v.trim();}
 function validate(data,old){const t={...old,...data};t.title=text(t.title,120,'标题');t.prompt=text(t.prompt,8000,'任务内容');if(!['chat','development'].includes(t.harness))fail('执行入口无效');if(/(?:\b(?:sk|ghp)[-_][A-Za-z0-9_-]{20,}|-----BEGIN .*PRIVATE KEY-----|(?:api[_-]?key|password|secret)\s*["']?\s*[:=]\s*["'][^"']{12,}["'])/i.test(t.prompt))fail('请勿在任务中保存凭据');
 const s=t.schedule;if(s?.type==='once'){const ms=Date.parse(s.at);if(!Number.isFinite(ms))fail('执行时间无效');t.schedule={type:'once',at:new Date(ms).toISOString()};}else if(s?.type==='interval'){const n=Number(s.everyMinutes);if(!Number.isFinite(n)||n<1||n>43200)fail('循环间隔需为1至43200分钟');let normalized;try{normalized=normalizeSchedulerInput({name:t.title,cwd:dataDir,prompt:t.prompt,kind:'interval',spec:n*60000,enabled:t.enabled},time());}catch(e){fail(e.message)}t.schedule={type:'interval',everyMinutes:Number(normalized.spec)/60000};}else fail('计划类型无效');
 if(t.enabled!==undefined&&typeof t.enabled!=='boolean')fail('enabled需为布尔值');t.enabled=t.enabled??false;
 if(t.maxRuns!=null&&(!Number.isSafeInteger(t.maxRuns)||t.maxRuns<1||t.maxRuns>100000))fail('maxRuns需为正整数');
 for(const k of ['sessionId','projectId','conversationId'])if(t[k]!=null)t[k]=text(t[k],200,k);
 if(t.memoryEnabled!==undefined&&typeof t.memoryEnabled!=='boolean')fail('memoryEnabled需为布尔值');t.memoryEnabled=t.memoryEnabled??false;
 return Object.fromEntries(['title','prompt','harness','sessionId','projectId','conversationId','memoryEnabled','schedule','enabled','maxRuns'].filter(k=>t[k]!==undefined).map(k=>[k,t[k]]));}
 function next(t){return t.schedule.type==='once'?t.schedule.at:new Date(computeNextFire({kind:'interval',spec:String(t.schedule.everyMinutes*60000)},time())).toISOString();}
 function assertOpen(){if(closed)fail('任务调度器已关闭',503);}
 function create(data){assertOpen();if(tasks.length>=100)fail('最多保存100项任务');const t={...validate(data),id:crypto.randomUUID(),createdAt:iso(),updatedAt:iso(),runCount:0,history:[],lastError:null};t.status=t.enabled?'idle':'paused';t.nextRunAt=t.enabled?next(t):null;tasks.push(t);save();emit('task_created',t);return clone(t);}
 function update(id,data){assertOpen();const t=get(id);if(t.workerCleanupRequired)fail('请先核实残留工作进程并清理任务隔离状态',409);if([...active.values()].some(a=>a.id===id))fail('运行中任务请先暂停或取消，结束后编辑',409);const v=validate(data,t);Object.assign(t,v,{updatedAt:iso(),status:v.enabled?'idle':'paused',nextRunAt:v.enabled?next(v):null});if(t.maxRuns&&t.runCount>=t.maxRuns){t.enabled=false;t.nextRunAt=null;t.status='paused';}save();emit('task_updated',t);return clone(t);}
 async function start(id,manual=false){if(closed)fail('任务调度器已关闭',503);const t=get(id);if(blockedHarnesses.has(t.harness))fail('此入口有未确认终止的工作进程，需先核实清理',409);if(active.has(t.harness))fail('此入口已有任务运行，稍后再试',409);if(t.maxRuns&&t.runCount>=t.maxRuns)fail('任务已达到次数上限',409);const controller=new AbortController(),entry={id,controller,phase:'checking'};active.set(t.harness,entry);
 try{if(await isBusy(t.harness,clone(t)))fail('此入口正在处理对话，稍后再试',409);}catch(e){if(active.get(t.harness)===entry)active.delete(t.harness);if(controller.signal.aborted){t.enabled=false;t.nextRunAt=null;t.status='paused';save();}throw e;}
 if(closed||controller.signal.aborted){active.delete(t.harness);t.status='paused';t.enabled=false;t.nextRunAt=null;save();fail('任务已取消',409);}
 entry.phase='running';
 const history={id:crypto.randomUUID(),startedAt:iso(),finishedAt:null,status:'running',manual};t.history=[history,...t.history].slice(0,SCHEDULER_HISTORY_MAX);t.runCount++;t.status='running';t.nextRunAt=null;t.lastError=null;t.updatedAt=iso();try{save()}catch(e){active.delete(t.harness);throw e;}emit('task_started',t);
 entry.done=(async()=>{try{const result=await runTask(clone(t),{signal:controller.signal,runId:history.id,onLinked:link=>{for(const key of ['conversationId','sessionId','workbenchClientId','sessionFile'])if(typeof link[key]==='string')history[key]=link[key].slice(0,key==='sessionFile'?2048:200);save();emit('task_linked',t);}});if(result&&typeof result==='object'){history.result={};for(const [key,max] of [['text',20000],['sessionFile',2048],['jobId',200],['conversationId',200],['workbenchConversationId',200],['sessionId',200],['workbenchClientId',200]])if(typeof result[key]==='string')history.result[key]=result[key].slice(0,max);}history.status=controller.signal.aborted?'cancelled':'completed';}catch(e){if(e?.code==='TERMINATION_FAILED'){t.workerCleanupRequired=true;t.enabled=false;blockedHarnesses.add(t.harness);}history.status=controller.signal.aborted&&e?.code!=='TERMINATION_FAILED'?'cancelled':'failed';history.error=String(e?.message||e).slice(0,1000);t.lastError=history.error;}finally{history.finishedAt=iso();if(controller.signal.aborted||t.schedule.type==='once'||(t.maxRuns&&t.runCount>=t.maxRuns))t.enabled=false;t.status=t.enabled?(history.status==='failed'?'error':'idle'):(history.status==='failed'?'error':'paused');t.nextRunAt=t.enabled?next(t):null;t.updatedAt=iso();active.delete(t.harness);try{save();emit('task_finished',t)}catch(e){emit('task_store_error',t,{error:String(e.message)})}}})();return clone(t);}
 function action(id,verb){assertOpen();const t=get(id),running=[...active.values()].find(a=>a.id===id);if(verb==='pause'){if(running?.phase==='checking')running.controller.abort();t.enabled=false;t.nextRunAt=null;if(!running)t.status='paused';}else if(verb==='resume'){if(blockedHarnesses.has(t.harness))fail('请先核实残留工作进程',409);if(running?.controller.signal.aborted)fail('正在停止，请等待结束后恢复',409);if(t.maxRuns&&t.runCount>=t.maxRuns)fail('任务已达到次数上限',409);t.enabled=true;if(!running){t.status='idle';t.nextRunAt=next(t);}}else if(verb==='cancel'){t.enabled=false;t.nextRunAt=null;if(running){t.status='cancelling';running.controller.abort();}else t.status='paused';}else fail('操作无效');t.updatedAt=iso();save();emit('task_'+verb,t);return clone(t);}
 function acknowledge(id,{executionChecked}={}){assertOpen();if(executionChecked!==true)fail('请先确认已核查上次执行结果',400);const t=get(id);if([...active.values()].some(a=>a.id===id))fail('运行中任务应先取消并等待结束',409);if(!t.workerCleanupRequired)fail('任务没有待确认的执行状态',409);t.workerCleanupRequired=false;t.enabled=false;t.nextRunAt=null;t.executionAcknowledgedAt=iso();t.updatedAt=iso();save();if(!tasks.some(x=>x.harness===t.harness&&x.workerCleanupRequired))blockedHarnesses.delete(t.harness);emit('task_acknowledged',t);return clone(t);}
 function remove(id){assertOpen();if(get(id).workerCleanupRequired)fail('请先核实残留工作进程并清理隔离状态',409);if([...active.values()].some(a=>a.id===id))fail('请先取消运行并等待结束',409);tasks=tasks.filter(t=>t.id!==id);save();return {ok:true};}
 async function tick(){if(closed)return;for(const t of tasks){if(!t.enabled||!t.nextRunAt||Date.parse(t.nextRunAt)>time()||active.has(t.harness))continue;try{await start(t.id,false)}catch(e){if(e.status!==409)emit('task_schedule_error',t,{error:String(e.message)});}}}
 const timer=setInterval(()=>{tick().catch(()=>{})},1000);timer.unref?.();
 async function readBody(req){const chunks=[];let n=0;for await(const b of req){n+=b.length;if(n>60000)fail('请求过大',413);chunks.push(b)}try{const v=JSON.parse(Buffer.concat(chunks).toString()||'{}');if(!v||typeof v!=='object'||Array.isArray(v))fail('JSON对象无效');return v}catch(e){if(e.status)throw e;fail('JSON格式无效')}}
 async function handle(req,res,url){const u=typeof url==='string'?new URL(url,'http://127.0.0.1'):url||new URL(req.url,'http://127.0.0.1');if(u.pathname!=='/api/tasks'&&!u.pathname.startsWith('/api/tasks/'))return false;const send=(status,data)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(data))};try{const remote=req.socket?.remoteAddress;if(!['127.0.0.1','::1','::ffff:127.0.0.1'].includes(remote))fail('仅支持本机访问',403);if(req.headers.origin){let host;try{host=new URL(req.headers.origin).host}catch{fail('Origin无效',403)}if(host!==req.headers.host)fail('来源不匹配',403)}const parts=u.pathname.split('/').filter(Boolean),id=parts[2];let result,status=200;
 if(parts.length===2&&req.method==='GET')result={tasks:clone(tasks)};
 else if(parts.length===2&&req.method==='POST'){result={task:create(await readBody(req))};status=201;}
 else if(parts.length===3&&req.method==='PATCH')result={task:update(id,await readBody(req))};
 else if(parts.length===3&&req.method==='DELETE')result=remove(id);
 else if(parts.length===4&&req.method==='POST'){if(parts[3]==='run'){result={task:await start(id,true),accepted:true};status=202;}else if(parts[3]==='acknowledge')result={task:acknowledge(id,await readBody(req))};else result={task:action(id,parts[3])};}
 else fail('任务接口不存在',404);send(status,result);}catch(e){send(e.status||500,{error:e.status?e.message:'任务服务处理失败'})}return true;}
 function close(){if(closed)return;closed=true;clearInterval(timer);for(const a of active.values()){const t=get(a.id);t.enabled=false;t.nextRunAt=null;t.status=a.phase==='running'?'cancelling':'paused';a.controller.abort();}save();}
 return {handle,tick,list:()=>clone(tasks),create,update,run:id=>start(id,true),pause:id=>action(id,'pause'),resume:id=>action(id,'resume'),cancel:id=>action(id,'cancel'),remove,acknowledge,close};
}
module.exports={createScheduler};
