/* Explicit local schedules. Opening this board never creates or runs a task. */
export function mountTaskBoard({doc=document,win=window,fetcher=fetch}={}){
 const el=(tag,text,cls)=>{const n=doc.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n};
 const btn=(text,fn,cls)=>{const b=el('button',text,cls);b.type='button';b.onclick=fn;return b};
 const field=(title,type='input')=>{const label=el('label'),input=el(type);input.setAttribute('aria-label',title);label.append(el('span',title),input);return {label,input}};
 const panel=el('dialog',undefined,'task-board');panel.setAttribute('aria-label','定时任务板');
 const launcher=btn('定时任务',()=>open(),'chip-btn');launcher.setAttribute('aria-haspopup','dialog');doc.querySelector('.top-actions')?.append(launcher);
 const header=el('header'),close=btn('关闭',()=>panel.close());header.append(el('h2','定时任务'),btn('刷新',()=>work(refresh)),close);
 const status=el('p','','task-status');status.setAttribute('role','status');status.setAttribute('aria-live','polite');
 const intro=el('p','任务保存在本机。服务运行时按计划执行；电脑休眠或服务关闭时不执行。任务在独立会话运行，不复制来源聊天上下文或草稿，请把要求写完整。启用或立即运行会向模型发送内容；开发任务可在所选项目目录执行工具，陪伴任务不使用工具。任务目前不检索项目记忆；项目仅用于确定执行目录。暂停仅停止后续计划，取消当前才会请求终止正在执行的任务。','task-muted');
 const form=el('form',undefined,'task-form'),title=field('任务标题'),prompt=field('要执行的内容','textarea'),target=field('目标模式','select'),schedule=field('执行计划','select'),at=field('执行时间（本机时区）'),interval=field('间隔分钟'),maxRuns=field('最多执行次数（可选）');
 for(const [v,t] of [['chat','陪伴聊天'],['development','开发工作台']]){const o=el('option',t);o.value=v;target.input.append(o)}target.input.value='chat';
 for(const [v,t] of [['once','执行一次'],['interval','循环执行']]){const o=el('option',t);o.value=v;schedule.input.append(o)}schedule.input.value='once';
 title.input.required=prompt.input.required=true;title.input.maxLength=120;prompt.input.maxLength=8000;prompt.input.rows=4;at.input.type='datetime-local';interval.input.type=maxRuns.input.type='number';interval.input.min=maxRuns.input.min='1';interval.input.max='43200';maxRuns.input.max='100000';interval.input.step=maxRuns.input.step='1';interval.input.value='30';
 const enabled=el('input');enabled.type='checkbox';enabled.checked=false;const consent=el('label',undefined,'task-consent');consent.append(enabled,el('span','保存后启用此计划（默认关闭）'));
 const scope=el('p','','task-muted'),save=el('button','保存任务');save.type='submit';save.className='task-primary';const reset=btn('新任务',()=>edit(null));const actions=el('div',undefined,'task-actions');actions.append(save,reset);
 form.append(title.label,prompt.label,target.label,scope,schedule.label,at.label,interval.label,maxRuns.label,consent,actions);
 const list=el('div',undefined,'task-list');panel.append(header,intro,status,form,el('h3','已保存任务'),list);doc.body.append(panel);
 let observed=null,editing=null,tasks=[],busy=false,lastFocus=null,timer=null,renderSignature=null,pendingTaskId=null;const taskCards=new Map();
 const notice=(text,error=false)=>{status.textContent=text;status.classList.toggle('error',error)};
 const dateText=value=>{const d=new Date(value);return value&&Number.isFinite(d.getTime())?d.toLocaleString():'—'};
 const json=(method,value)=>({method,headers:{'Content-Type':'application/json'},body:JSON.stringify(value)});
 async function request(path,options){const r=await fetcher(path,options);const type=r.headers?.get?.('content-type');if(type&&!type.includes('json'))throw Error('任务服务尚未就绪，请稍后刷新重试');const data=await r.json();if(!r.ok)throw Error(data.error||`请求失败 (${r.status})`);return data}
 async function work(fn){if(busy)return;busy=true;panel.setAttribute('aria-busy','true');const controls=[...panel.querySelectorAll('button,input,select,textarea')].filter(n=>n!==close).map(n=>[n,n.disabled]);controls.forEach(([n])=>n.disabled=true);try{await fn()}catch(e){notice(e.message,true)}finally{busy=false;panel.setAttribute('aria-busy','false');controls.forEach(([n,d])=>n.disabled=d)}}
 function updateSchedule(){at.label.hidden=schedule.input.value!=='once';interval.label.hidden=schedule.input.value!=='interval';at.input.required=!at.label.hidden;interval.input.required=!interval.label.hidden}
 schedule.input.onchange=updateSchedule;
 function selectedScope(){if(editing&&editing.harness===target.input.value)return {sessionId:editing.sessionId,conversationId:editing.conversationId};return target.input.value==='development'?(observed||{}):{sessionId:win.piActiveSessionId}}
 function updateScope(){const s=selectedScope();scope.textContent='执行项目：'+(editing?.projectId||win.piMemoryProjectId||'default')+' · 独立运行'+(s?.sessionId?' · 来源会话：'+s.sessionId:' · 未关联来源会话');}
 target.input.onchange=updateScope;
 win.addEventListener('message',e=>{const frame=doc.querySelector('.workbench-home iframe');if(!frame||e.origin!==win.location.origin||e.source!==frame.contentWindow||e.data?.source!=='pichan-workbench'||e.data.event!=='status')return;const {sessionId,conversationId}=e.data.detail||{};observed=typeof sessionId==='string'&&typeof conversationId==='string'?{sessionId,conversationId}:null;updateScope()});
 function edit(task){editing=task;title.input.value=task?.title||'';prompt.input.value=task?.prompt||'';target.input.value=task?.harness||'chat';schedule.input.value=task?.schedule?.type||'once';const d=task?.schedule?.at?new Date(task.schedule.at):null;at.input.value=d&&Number.isFinite(d.getTime())?new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16):'';interval.input.value=String(task?.schedule?.everyMinutes||30);maxRuns.input.value=task?.maxRuns?String(task.maxRuns):'';enabled.checked=task?.enabled===true;save.textContent=task?'保存修改':'保存任务';updateSchedule();updateScope();}
 const labels={idle:'待机',running:'执行中',paused:'已暂停',error:'出错',interrupted:'已中断',cancelling:'正在取消',completed:'已完成',success:'成功',failed:'失败',cancelled:'已取消'};
 function render(){taskCards.clear();list.replaceChildren();if(!tasks.length){list.append(el('p','还没有任务。填写内容并保存；未勾选启用的任务不会自动运行。','task-muted'));return}for(const task of tasks){const card=el('article',undefined,'task-card'),running=['running','cancelling'].includes(task.status);card.append(el('h4',task.title),el('p',task.prompt,'task-content'),el('p',`${task.harness==='development'?'开发':'陪伴'} · ${labels[task.status]||task.status} · ${task.enabled?'计划已启用':'计划已关闭'} · 已执行 ${task.runCount||0} 次`,'task-muted'),el('p','下次执行：'+dateText(task.nextRunAt),'task-muted'),el('p','项目：'+(task.projectId||'default')+' · 来源会话：'+(task.sessionId||'无')+(task.conversationId?' · '+task.conversationId:''),'task-muted'));
 if(task.workerCleanupRequired){const warning=el('p','执行状态待核实，计划已隔离。请先检查残留进程、日志和执行结果；核实后仍保持计划关闭，不会自动重跑。','task-error');warning.setAttribute('role','alert');const acknowledge=btn('我已核实残留进程与执行结果',()=>work(async()=>{if(!win.confirm('确认你已检查并处理残留工作进程，核对日志与执行结果？解除隔离后计划仍关闭，不会自动重新运行。'))return;await request(`/api/tasks/${encodeURIComponent(task.id)}/acknowledge`,json('POST',{executionChecked:true}));await refresh();notice('隔离已解除；计划保持关闭，未重新执行')}));acknowledge.disabled=running;card.append(warning,acknowledge);}if(task.lastError)card.append(el('p',task.lastError,'task-error'));const buttons=el('div',undefined,'task-actions');const act=(text,action,confirmText)=>btn(text,()=>work(async()=>{if(confirmText&&!win.confirm(confirmText))return;await request(`/api/tasks/${encodeURIComponent(task.id)}/${action}`,{method:'POST'});await refresh();notice(text+'请求已处理')}));const run=act('立即运行','run');run.disabled=task.workerCleanupRequired===true||running||!!(task.maxRuns&&task.runCount>=task.maxRuns);const pause=act(task.enabled?'暂停计划':'恢复计划',task.enabled?'pause':'resume');pause.disabled=task.workerCleanupRequired===true||task.status==='cancelling'||(!task.enabled&&!!(task.maxRuns&&task.runCount>=task.maxRuns));const cancel=act('取消当前','cancel','确定取消当前执行？已完成的工具操作不会撤销。');cancel.disabled=!running||task.status==='cancelling';const change=btn('编辑',()=>{edit(task);title.input.focus()});change.disabled=running||task.workerCleanupRequired===true;const remove=btn('删除',()=>work(async()=>{if(!win.confirm(`删除任务「${task.title}」及其运行记录？`))return;await request(`/api/tasks/${encodeURIComponent(task.id)}`,{method:'DELETE'});if(editing?.id===task.id)edit(null);await refresh();notice('任务已删除')}),'task-danger');remove.disabled=running||task.workerCleanupRequired===true;buttons.append(run,pause,cancel,change,remove);card.append(buttons);
 const history=el('details'),summary=el('summary','运行记录（'+(task.history?.length||0)+'）');history.append(summary);if(!task.history?.length)history.append(el('p','尚未执行','task-muted'));for(const h of (task.history||[])){history.append(el('p',`${dateText(h.startedAt)} → ${dateText(h.finishedAt)} · ${labels[h.status]||h.status}${h.error?' · '+h.error:''}`,'task-muted'));if(h.result?.text)history.append(el('p',h.result.text,'task-content'));if(h.result?.jobId)history.append(el('p','独立运行：'+h.result.jobId,'task-muted'));}card.append(history);card.tabIndex=-1;taskCards.set(task.id,{card,history});list.append(card)}}
 function revealTask(){if(!pendingTaskId)return;const entry=taskCards.get(pendingTaskId);if(!entry){notice('该任务已不存在或暂未加载，请刷新重试',true);return;}pendingTaskId=null;entry.history.open=true;entry.card.scrollIntoView({block:'start',behavior:'auto'});entry.card.focus({preventScroll:true});}
 async function refresh(){const result=await request('/api/tasks');tasks=result.tasks||[];const signature=JSON.stringify(tasks);if(signature!==renderSignature){render();renderSignature=signature;}updateScope();notice(tasks.length+' 个任务');revealTask();win.dispatchEvent(new win.CustomEvent('pi-tasks-updated',{detail:{reason:'refresh'}}))}
 form.onsubmit=e=>{e.preventDefault();work(async()=>{const s=selectedScope();if(schedule.input.value==='once'&&!Number.isFinite(Date.parse(at.input.value)))throw Error('请选择有效执行时间');const plan=schedule.input.value==='once'?{type:'once',at:new Date(at.input.value).toISOString()}:{type:'interval',everyMinutes:Number(interval.input.value)};if(plan.type==='once'&&enabled.checked&&Date.parse(plan.at)<=Date.now())throw Error('执行时间需要晚于当前时间');if(plan.type==='interval'&&(!Number.isInteger(plan.everyMinutes)||plan.everyMinutes<1||plan.everyMinutes>43200))throw Error('循环间隔需为 1 至 43200 分钟整数');const limit=maxRuns.input.value?Number(maxRuns.input.value):null;if(limit!==null&&(!Number.isInteger(limit)||limit<1||limit>100000))throw Error('执行次数需为 1 至 100000 的整数');await request(editing?'/api/tasks/'+encodeURIComponent(editing.id):'/api/tasks',json(editing?'PATCH':'POST',{title:title.input.value.trim(),prompt:prompt.input.value.trim(),harness:target.input.value,...s,projectId:editing?.projectId||win.piMemoryProjectId||'default',schedule:plan,enabled:enabled.checked===true,memoryEnabled:false,maxRuns:limit}));edit(null);await refresh();notice('任务已保存；只有启用的计划会自动执行')})};
 async function open(taskId){pendingTaskId=typeof taskId==='string'?taskId:null;if(!panel.open){lastFocus=doc.activeElement;panel.showModal()}updateScope();await work(refresh);if(panel.open&&!timer)timer=win.setInterval(()=>{if(panel.open&&!busy&&!form.contains(doc.activeElement)&&!list.contains(doc.activeElement))work(refresh)},10000)}
 panel.addEventListener('close',()=>{if(timer)win.clearInterval(timer);timer=null;lastFocus?.focus?.()});win.addEventListener('pagehide',()=>{if(timer)win.clearInterval(timer);timer=null});edit(null);
 win.piTaskBoard={open};
 return {open,panel,launcher};
}
if(typeof document!=='undefined')mountTaskBoard();
